package eu.kanade.tachiyomi.animeextension.en.hanime

import android.annotation.SuppressLint
import android.app.Application
import android.os.Handler
import android.os.Looper
import android.webkit.CookieManager
import android.webkit.JavascriptInterface
import android.webkit.WebResourceRequest
import android.webkit.WebResourceResponse
import android.webkit.WebView
import android.webkit.WebViewClient
import uy.kohesive.injekt.Injekt
import uy.kohesive.injekt.api.get
import java.util.concurrent.CountDownLatch
import java.util.concurrent.TimeUnit

data class HlsResult(
    val url: String,
    val cookies: String,
)

object WebViewExtractor {

    private const val USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) " +
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

    // Intercepts the HLS m3u8 URL that the player requests when a video page loads.
    // The token embedded in the URL is generated by the WASM module — we let the
    // browser do that naturally and intercept the resulting request via two methods:
    //   1. JS injection overriding window.fetch and XHR (catches MSE player requests)
    //   2. shouldInterceptRequest as fallback for native media element requests
    @SuppressLint("SetJavaScriptEnabled", "AddJavascriptInterface")
    fun extractHlsUrl(videoPageUrl: String): HlsResult? {
        val latch = CountDownLatch(1)
        var hlsUrl = ""
        var cookies = ""
        val context = Injekt.get<Application>()

        Handler(Looper.getMainLooper()).post {
            val webView = WebView(context)
            webView.settings.apply {
                javaScriptEnabled = true
                domStorageEnabled = true
                // Allow autoplay so the player starts without user interaction
                mediaPlaybackRequiresUserGesture = false
                userAgentString = USER_AGENT
            }

            // JS interface — called from injected JS when an HLS URL is detected
            webView.addJavascriptInterface(
                object : Any() {
                    @JavascriptInterface
                    fun onHlsUrl(url: String) {
                        if (hlsUrl.isNotEmpty()) return
                        hlsUrl = url
                        cookies = CookieManager.getInstance()
                            .getCookie("https://hanime.tv") ?: ""
                        Handler(Looper.getMainLooper()).post { webView.destroy() }
                        latch.countDown()
                    }
                },
                "AndroidHls",
            )

            webView.webViewClient = object : WebViewClient() {
                override fun onPageFinished(view: WebView, url: String) {
                    // Inject monitoring script to intercept window.fetch and XHR.
                    // Also simulate a click on the play button in case autoplay is blocked.
                    view.evaluateJavascript(
                        """
                        (function() {
                            var orig = window.fetch;
                            window.fetch = function() {
                                var u = typeof arguments[0] === 'string'
                                    ? arguments[0]
                                    : (arguments[0] && arguments[0].url) || '';
                                if (u && u.indexOf('/hls/') !== -1 && u.indexOf('hanime.tv') !== -1) {
                                    AndroidHls.onHlsUrl(u);
                                }
                                return orig.apply(this, arguments);
                            };
                            var origOpen = XMLHttpRequest.prototype.open;
                            XMLHttpRequest.prototype.open = function(method, url) {
                                if (url && url.indexOf('/hls/') !== -1 && url.indexOf('hanime.tv') !== -1) {
                                    AndroidHls.onHlsUrl(url);
                                }
                                return origOpen.apply(this, arguments);
                            };
                            // Attempt to click play button if autoplay didn't start
                            setTimeout(function() {
                                var candidates = [
                                    document.querySelector('button[aria-label="Play"]'),
                                    document.querySelector('[class*="play"]'),
                                    document.querySelector('video')
                                ];
                                for (var i = 0; i < candidates.length; i++) {
                                    if (candidates[i]) { candidates[i].click(); break; }
                                }
                            }, 2000);
                        })();
                        """.trimIndent(),
                        null,
                    )
                }

                // Fallback: catch the HLS URL if the player uses a native <video> element
                override fun shouldInterceptRequest(
                    view: WebView,
                    request: WebResourceRequest,
                ): WebResourceResponse? {
                    val url = request.url.toString()
                    if (hlsUrl.isEmpty() &&
                        url.contains("/hls/") &&
                        url.contains("hanime.tv")
                    ) {
                        hlsUrl = url
                        cookies = CookieManager.getInstance()
                            .getCookie("https://hanime.tv") ?: ""
                        Handler(Looper.getMainLooper()).post { webView.destroy() }
                        latch.countDown()
                    }
                    return null
                }
            }

            webView.loadUrl(videoPageUrl)
        }

        // Wait up to 45 seconds — WASM init + handshake can be slow
        latch.await(45, TimeUnit.SECONDS)
        return if (hlsUrl.isNotEmpty()) HlsResult(hlsUrl, cookies) else null
    }
}
